targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        enabled: true
        options:
          auto_register: true
          # Generates config for $initGetIt function
          generate_for:
            - lib/core/di/injection.dart
